# Generated by Django 5.0 on 2024-01-21 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='couponDiscount',
            new_name='coupon_discount',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='createdAt',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='deliveryFee',
            new_name='delivery_fee',
        ),
        migrations.RenameField(
            model_name='cartitem',
            old_name='bookItem',
            new_name='book_item',
        ),
        migrations.RenameField(
            model_name='cartitem',
            old_name='unitPrice',
            new_name='unit_price',
        ),
        migrations.RenameField(
            model_name='coupon',
            old_name='couponCode',
            new_name='coupon_code',
        ),
        migrations.RenameField(
            model_name='coupon',
            old_name='minimumPurchase',
            new_name='minimum_purchase',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='createdAt',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='deliveryAddress',
            new_name='delivery_address',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='couponDiscount',
            new_name='delivery_fee',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='orderStatus',
            new_name='order_status',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='paymentStatus',
            new_name='payment_status',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='bookItem',
            new_name='book_item',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='unitPrice',
            new_name='unit_price',
        ),
        migrations.RenameField(
            model_name='sellerwallet',
            old_name='totalAmount',
            new_name='total_amount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='deliveryFee',
        ),
        migrations.AddField(
            model_name='order',
            name='coupon_discount',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
