# Generated by Django 5.0.1 on 2024-02-11 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0001_initial'),
        ('community', '0008_alter_customer_birth_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoneyWithdrawHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('payment_method', models.CharField(choices=[('B', 'Bkash'), ('N', 'Nagad')], max_length=1)),
                ('payment_account_no', models.CharField(max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='community.seller')),
            ],
        ),
    ]
