# Generated by Django 5.0.1 on 2024-02-11 10:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0002_moneywithdrawhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moneywithdrawhistory',
            name='amount',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(20, "You can't withdraw less than 20 taka"), django.core.validators.MaxValueValidator(20000, "You can't withdraw more than 20000 taka")]),
        ),
    ]
