# Generated by Django 5.0.1 on 2024-02-11 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0003_alter_moneywithdrawhistory_amount'),
        ('community', '0008_alter_customer_birth_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MoneyWithdrawHistory',
            new_name='MoneyWithdraw',
        ),
    ]
