# Generated by Django 5.0.1 on 2024-02-18 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0004_rename_moneywithdrawhistory_moneywithdraw'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='confirmed_by_seller',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='transferred_to_inventory',
            field=models.BooleanField(default=False),
        ),
    ]
