# Generated by Django 5.0.1 on 2024-02-19 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0005_orderitem_confirmed_by_seller_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('P', 'pending'), ('C', 'confirmed'), ('O', 'delivery ongoing'), ('D', 'delivered'), ('F', 'failed')], default='P', max_length=1),
        ),
    ]
