# Generated by Django 5.0.1 on 2024-02-01 09:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0011_alter_cartitem_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(30, "You can't order more than 30 pieces"), django.core.validators.MinValueValidator(1, 'Quantity should be at least 1')]),
        ),
    ]
