# Generated by Django 5.0.1 on 2024-02-08 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0013_alter_order_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('P', 'pending'), ('R', 'received')], default='P', max_length=1),
        ),
    ]
