# Generated by Django 5.0.1 on 2024-02-08 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0017_sellinghistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellinghistory',
            name='unit_price',
            field=models.PositiveSmallIntegerField(default='0'),
            preserve_default=False,
        ),
    ]
