# Generated by Django 5.0.1 on 2024-02-08 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0018_sellinghistory_unit_price'),
        ('community', '0008_alter_customer_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellinghistory',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.seller'),
        ),
    ]
