# Generated by Django 5.0.1 on 2024-02-10 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0019_alter_sellinghistory_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellinghistory',
            name='money_transferred',
            field=models.BooleanField(default=False),
        ),
    ]
