# Generated by Django 5.0.1 on 2024-02-10 10:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0020_sellinghistory_money_transferred'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellinghistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
