# Generated by Django 5.0 on 2024-01-21 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_remove_genre_featuredbook'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='writer',
            options={'ordering': ['name']},
        ),
    ]
