# Generated by Django 5.0 on 2024-01-21 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0004_alter_genre_options_alter_writer_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={},
        ),
        migrations.RemoveField(
            model_name='bookitem',
            name='discountedPrice',
        ),
    ]
