# Generated by Django 5.0 on 2024-01-21 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0005_alter_book_options_remove_bookitem_discountedprice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookitem',
            old_name='unitPrice',
            new_name='unit_price',
        ),
    ]
