# Generated by Django 5.0 on 2024-01-21 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0006_rename_unitprice_bookitem_unit_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='createdAt',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='bookitem',
            old_name='createdAt',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='genre',
            old_name='featuredBook',
            new_name='featured_book',
        ),
        migrations.RenameField(
            model_name='writer',
            old_name='createdAt',
            new_name='created_at',
        ),
    ]
