# Generated by Django 5.0 on 2024-01-22 22:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0008_alter_bookitem_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='rating',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(1, 'Rating cannot be less than 1'), django.core.validators.MaxValueValidator(10, 'Rating cannot exceed 10')]),
        ),
    ]
