# Generated by Django 5.0.1 on 2024-01-27 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0010_alter_genre_description_alter_genre_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writer',
            name='about',
            field=models.TextField(),
        ),
    ]
