# Generated by Django 5.0.1 on 2024-01-31 09:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0011_alter_writer_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='posted_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
