# Generated by Django 5.0.1 on 2024-02-03 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0014_alter_book_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='book',
            unique_together={('title', 'writer')},
        ),
    ]
