# Generated by Django 5.0.1 on 2024-02-19 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0015_alter_book_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookitem',
            name='description',
        ),
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.CharField(default='', max_length=1500),
            preserve_default=False,
        ),
    ]
