# Generated by Django 5.0.1 on 2024-02-19 08:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0016_remove_bookitem_description_book_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='rating',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0, 'Rating cannot be less than 0'), django.core.validators.MaxValueValidator(10, 'Rating cannot exceed 10')]),
        ),
    ]
