# Generated by Django 5.0.1 on 2024-02-19 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0017_alter_feedback_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookitem',
            name='sold_units',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
