# Generated by Django 5.0 on 2023-12-17 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='phoneNo',
            field=models.CharField(default=0, max_length=12),
            preserve_default=False,
        ),
    ]
