# Generated by Django 5.0 on 2024-01-21 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_seller_phoneno'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='joined_at',
            new_name='joinedAt',
        ),
        migrations.RenameField(
            model_name='seller',
            old_name='joined_at',
            new_name='joinedAt',
        ),
    ]
