# Generated by Django 5.0 on 2024-01-21 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_rename_joined_at_customer_joinedat_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='birthDate',
            new_name='birth_date',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='joinedAt',
            new_name='joined_at',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='phoneNo',
            new_name='phone_no',
        ),
        migrations.RenameField(
            model_name='seller',
            old_name='birthDate',
            new_name='birth_date',
        ),
        migrations.RenameField(
            model_name='seller',
            old_name='brandName',
            new_name='brand_name',
        ),
        migrations.RenameField(
            model_name='seller',
            old_name='joinedAt',
            new_name='joined_at',
        ),
        migrations.RenameField(
            model_name='seller',
            old_name='phoneNo',
            new_name='phone_no',
        ),
    ]
