# Generated by Django 5.0.1 on 2024-01-31 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0005_alter_customer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='brand_name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
